### PR TITLE
Remove HOOMD dependencies from neighbor library

### PR DESCRIPTION
**Pull request by mphoward**
HOOMD was mainly used for three things in neighbor: (1) math, (2) memory management, and (3) autotuning. 

1. Math was pretty easy to get rid of since most of the types in neighbor were already float3 (rather than Scalar3), but there are a few instances where Scalars have been permanently changed to floats. It is now the responsibility of the caller to ensure that any doubles are cast appropriately here. Everywhere else, templated operations are used, so the caller can decide what precision to use internally, and then the data can be coerced into floats as before.

2. All internal GPU arrays have been converted to thrust vectors. (Other containers would also be OK.) This change was also relatively easy to support since most times the caller is interfacing with the library through raw pointers, which are wrapped by the various insert / query ops.

3. HOOMD's autotuner needed to be copied over and modified. neighbor now can be included directly in CUDA code, and so it was not allowable to use some of the functions or objects inside it (and this is also too heavy for what the autotuner is actually doing). The functionality is essentially the same.

The files are now organized similarly to pybind11, and the cmake project should export itself as a proper interface library on installation (I think). One issue is that neighbor does depend on CUB, which does not have internal CMake support. I needed to write a little FindCUB script, and I don't know if this has been implemented / installed properly.

The unit tests make use of upp11 as an external library, which also has a CMake find package routine. If this is too annoying, I can add it as a submodule. upp11 is header-only, so it's relatively easy to clone yourself.

I decided to remove support for the `UniformGrid`. It was getting annoying maintaining two types of objects. Also, the `UniformGrid` depended much more heavily on HOOMD and would be harder to break. It also did not support the full templated API of the LBVH. Any neighbor algorithms that I add in future will be required to share this API.

### CODE REVIEW

**Comment by mphoward** [comment]
@jglaser This is ready for your feedback!

**Comment by jglaser** [comment]
This looks good in general, assuming that any outstanding build problems are solved. A few remarks:

- In view of https://github.com/glotzerlab/hoomd-blue/issues/543 (multi-GPU support in `nlist.tree()`), should we proactively use managed memory inside the `thrust::device_vector`s? One possible approach would be to use a custom allocator, see here
https://devtalk.nvidia.com/default/topic/987577/-thrust-is-there-a-managed_vector-with-unified-memory-do-we-still-only-have-device_vector-cuda-thrust-managed-vectors-/
Managed memory will be slower to allocate, but you're already amortizing all allocations.

- Is code duplication of the `Autotuner` really necessary? We might revisit the `Autotuner` interface for 3.0 and make it possible to store the tuning parameters inside as a state, say, a .gsd. (issue/PR to be created). This would change the interface, and make an update of the neighbor library necessary, in addition to that of NeighborListGPUTree.*. Would it be possible for the library routines to take the block size or any other autotuning parameters as arguments, and default to some sensible heuristic otherwise?

- The benchmarks still seem to depend on `HOOMDMath.h` / `Scalar4`. Is this intended?

**Comment by mphoward** [comment]
> * In view of [glotzerlab/hoomd-blue#543](https://github.com/glotzerlab/hoomd-blue/issues/543) (multi-GPU support in `nlist.tree()`), should we proactively use managed memory inside the `thrust::device_vector`s? One possible approach would be to use a custom allocator, see here
>   https://devtalk.nvidia.com/default/topic/987577/-thrust-is-there-a-managed_vector-with-unified-memory-do-we-still-only-have-device_vector-cuda-thrust-managed-vectors-/
>   Managed memory will be slower to allocate, but you're already amortizing all allocations.

Sure, I'm not married to using thrust, and I would have preferred to use malloc & free if it wasn't such a pain. :-) I'm not sure we even need all the bells and whistles that thrust provides, so what if I define a lightweight `neighbor::device_ptr` with `get()`, `size()`, and `swap()` methods. The allocation / deallocation can be done with managed memory.

> * Is code duplication of the `Autotuner` really necessary? We might revisit the `Autotuner` interface for 3.0 and make it possible to store the tuning parameters inside as a state, say, a .gsd. (issue/PR to be created). This would change the interface, and make an update of the neighbor library necessary, in addition to that of NeighborListGPUTree.*. Would it be possible for the library routines to take the block size or any other autotuning parameters as arguments, and default to some sensible heuristic otherwise?

I needed to duplicate this class because it needs both an execution configuration and pybind11, making it incompatible with a header-only library that works with nvcc. That being said, I don't really like the autotuner as implemented anyway because it breaks stream concurrency (the CUDA events are put in the default stream, and even if this were changed, the tuners force stream synchronization to read off the events). I could supply launch parameters based on a heuristic, at the possible expense of performance. I'm not sure that exposing the kernel launch parameters to the caller necessarily makes sense. How would the caller make use of this if they don't have access to the kernel timings at runtime (only by the profiler?)? @joaander do you also have any feedback on this point?

> * The benchmarks still seem to depend on `HOOMDMath.h` / `Scalar4`. Is this intended?

Yes, that is intended because I like the benchmarks to be for real GSD files, not just some configuration I made up. The benchmarks find HOOMD as a package to supply these dependencies. Eventually I will find a way to make the benchmark files available.

**Comment by jglaser** [comment]
I like the use of the internal `neighbor::device_ptr`, which would be smart pointer (`std::unique_ptr<>`) right? And not requiring thrust would be a plus.

Regarding the autotuning, I can think of several possible minimal solutions on the C++ level. You could 

- expose the internal autotuner object, and provide with some simple methods to query the state (for the future)
- Define a minimal Autotuner model (`begin`,`end`, `getParam`()) and template the classes on the tuner, to make it possible to provide an autotuner argument (or use the built-in one when none is provided)
- Leave tuning to the user, but supply a list of valid inputs (block sizes) via `getValidTuningParams()`, a single one of which would (optionally) be provided to the API method at every time.

I am not aware of any other standard solutions to the tuning interface problem. I know that CUB thrust etc. have their own heuristics built-in, which are probably close to optimal most of the time, but they also do not provide the possibility for the user to auto-tune on their side. These libraries do allow running on user-supplied streams, on the other hand.

Regarding, the streams issue, yes, the `Autotuner` events are created on stream zero, and therefore trigger implicit synchronization. This results in measuring the effective launch time for all concurrent streams together.  Would you want to split that up further (into a tuning parameter per type pair, say?)? Or, it looks like currently there is one tuner call per type pair. I see how can that break concurrency during tuning (and also lead to less accurate results). I believe this also would be solved by letting the user do the tuning (lump all asynchronous API calls together between a `tuner->begin()` and `tuner->end()`).

All of these suggestions involve a little bit of extra work on the API side, but may result in a more adaptable implementation.

**Comment by mphoward** [comment]
> * expose the internal autotuner object, and provide with some simple methods to query the state (for the future)

This is certainly possible if your goal is to be able to record the state of the autotuner. Each autotuner is a unique pointer, though, so how would you want the data to be accessible or returned? One way is to return a vector holding the current parameter for all tuners in the object, and the state could be restored again using a vector.

> * Define a minimal Autotuner model (`begin`,`end`, `getParam`()) and template the classes on the tuner, to make it possible to provide an autotuner argument (or use the built-in one when none is provided)

This sounds like a decent amount of work, so I don't think I want to try this unless you have a new autotuner API in mind. I'm concerned that you might still need to expose some internals of the tuners, etc.

> * Leave tuning to the user, but supply a list of valid inputs (block sizes) via `getValidTuningParams()`, a single one of which would (optionally) be provided to the API method at every time.

This would probably be the most flexible option, since then the user can wrap the function in whatever tuner they like, or lump multiple objects into the same tuner. One issue, though, is that a single call to a neighbor API function like `build` or `traverse` can invoke multiple kernels. Would you assume that the same autotuner parameter should be supplied to all of these kernels?
 
> Regarding, the streams issue, yes, the `Autotuner` events are created on stream zero, and therefore trigger implicit synchronization. This results in measuring the effective launch time for all concurrent streams together. Would you want to split that up further (into a tuning parameter per type pair, say?)? Or, it looks like currently there is one tuner call per type pair. I see how that can break concurrency during tuning (and also lead to less accurate results). I believe this also would be solved by letting the user do the tuning (lump all asynchronous API calls together between a `tuner->begin()` and `tuner->end()`).

As implemented in HOOMD, there is one LBVH and one LBVHTraverser per type. Each of these holds their own tuners, which are updated every time the method is invoked. The LBVH has a blocking call in it because of how CUB does the sorting, but the LBVHTraversers can be concurrent in multiple streams if the tuners are not currently running. So, allowing the user to wrap all of these in a tuner (using one shared parameter) would give one way to avoid the synchronization in traversal. I don't think there is an performant way to avoid it in CUB (I tried, but took a performance hit).

**Comment by jglaser** [comment]
> > * Leave tuning to the user, but supply a list of valid inputs (block sizes) via `getValidTuningParams()`, a single one of which would (optionally) be provided to the API method at every time.
> 
> This would probably be the most flexible option, since then the user can wrap the function in whatever tuner they like, or lump multiple objects into the same tuner.

agreed
> One issue, though, is that a single call to a neighbor API function like `build` or `traverse` can invoke multiple kernels. Would you assume that the same autotuner parameter should be supplied to all of these kernels?
> 

Several options:

1. Using the same autotuning parameter is possible if all kernels share the same parameter layout (i.e., a single block size). In this case, the optimal tuning parameter would be determined by the kernel that dominates the run time (which is desired), so it would still work.

2. Alternatively, if the goal is to tune every kernel, including the ones with a shorter run time, they could be included in the tuning parameter. You can reasonably pack up to three block sizes into one `unsigned int`. The disadvantage is that with every extra packed kernel parameter, the tuning time squares (or triples).

3. Or, if two or more kernel calls inside the API method take about equal time, it would make sense to split the API call into two (or more), to enable individual tuning.

4. Or, give fixed block sizes to the kernels that are expected to not be dominant.

> > Regarding, the streams issue, yes, the `Autotuner` events are created on stream zero, and therefore trigger implicit synchronization. This results in measuring the effective launch time for all concurrent streams together. Would you want to split that up further (into a tuning parameter per type pair, say?)? Or, it looks like currently there is one tuner call per type pair. I see how that can break concurrency during tuning (and also lead to less accurate results). I believe this also would be solved by letting the user do the tuning (lump all asynchronous API calls together between a `tuner->begin()` and `tuner->end()`).
> 
> As implemented in HOOMD, there is one LBVH and one LBVHTraverser per type. Each of these holds their own tuners, which are updated every time the method is invoked. The LBVH has a blocking call in it because of how CUB does the sorting, but the LBVHTraversers can be concurrent in multiple streams if the tuners are not currently running. So, allowing the user to wrap all of these in a tuner (using one shared parameter) would give one way to avoid the synchronization in traversal. I don't think there is an performant way to avoid it in CUB (I tried, but took a performance hit).

I see there is a `cudaStreamSynchronize()` in `lbvh_sort_codes()` (I don't exactly know why, but assume it is there for a reason). I don't think that's a concern, per se, since neighbor lists are built infrequently. If the concern was that the tuning is dominated by sorting time, well.... it would still be possible to tune the other kernels, but the effect would be smaller. It just would be a not completely asynchronous interface, which is fine, no? 

More importantly, the streams are already exposed for the traverser, which is good.

**Comment by jglaser** [comment]
Adding to the last comment, yes, if the goal is to also run tree construction concurrently, and not only the traversal, one would have to avoid the sync in the sorter and run CUB `deviceRadixSort::sortPairs()` asynchronously (which I believe is possible). But as you said, if performance takes a hit, that may not be worth it.

**Comment by mphoward** [comment]
OK, this sounds like the plan should then be to:

1. Try using one tunable block size for each API call, which may be used to invoke multiple kernels. Depending on benchmarks and profiling, we can consider fixing the block size for some kernels if this turns out to decrease performance significantly.
2. Expose the valid autotuner parameters to the caller as a vector.
3. Allow the user to set the tuner parameter however they like from this list, with some sensible default value chosen by us.

The reason for the synchronization in `lbvh_sort_codes` is to ensure that sorting has completed before checking which array in `cub::DoubleBuffer` holds the sorted data (it's not documented whether this synchronization occurs internally). If the sorted data is in the wrong array, the double buffer arrays are swapped before proceeding to the next kernel, which creates the stream synchronization point. CUB has an alternative signature for `cub::DeviceRadixSort` that ensures the sorted array ends up in a certain output array, but when I tried using it, it seemed to make the performance significantly slower. We can try this again to see if it makes a difference. I decided at the time that it was more important to get concurrency in the traversal (where there are Ntypes^2 launches), and I let the build slide.

I think it's OK that `build` allows use of the stream but is not fully asynchronous. For example, if the user does not call `setup` before `build`, `build` can still execute in stream but will synchronize if it has to do any mallocs. thrust has many functions like this.

**Comment by mphoward** [comment]
- [ ] Replace `thrust::device_vector` by `neighbor::device_ptr`
- [ ] Remove `Autotuner`
- [ ] Add API to set block parameters, with sensible defaults chosen by some profiling.

**Comment by jglaser** [comment]
> The reason for the synchronization in `lbvh_sort_codes` is to ensure that sorting has completed before checking which array in `cub::DoubleBuffer` holds the sorted data (it's not documented whether this synchronization occurs internally).

Oh, ok, the CUB docs (https://nvlabs.github.io/cub/structcub_1_1_device_radix_sort.html) just state:
'Upon completion, the sorting operation will update the "current" indicator within each DoubleBuffer wrapper to reference which of the two buffers now contains the sorted output sequence (a function of the number of key bits specified and the targeted device architecture).'

If indeed, *upon completion* means at the end of the kernel execution (and after a possible synchronization), it is not clear whether the user needs to synchronize or not. If somehow the buffer swap is the last operation in the kernel call, it would indeed require synchronization before touching the pointers on the host. They may have avoided this scenario by using a copy of the pointer as it was at the beginning of the sort (copying at the host side). FWIW, one could just try to remove the sync and see what happens or look at the cub code. If one wants to be extra safe, just leave it as is, or defer the change to later.

> If the sorted data is in the wrong array, the double buffer arrays are swapped before proceeding to the next kernel, which creates the stream synchronization point. CUB has an alternative signature for `cub::DeviceRadixSort` that ensures the sorted array ends up in a certain output array, but when I tried using it, it seemed to make the performance significantly slower. We can try this again to see if it makes a difference. I decided at the time that it was more important to get concurrency in the traversal (where there are Ntypes^2 launches), and I let the build slide.

Agreed.

**Comment by jglaser** [comment]
In addition, since the selection of the output buffer is not predictable ('a function of the number of key bits specified and the targeted device architecture') one cannot store the pointer beforehand to know where the output result ends up. It thus seems like one has to wait for the kernel. Unless 'upon completion of the sorting operation' means after leaving the asynchronous CUB API call. Anyway.

**Comment by jglaser** [comment]
A quick look at

https://github.com/NVlabs/cub/blob/1.8.0/cub/device/dispatch/dispatch_radix_sort.cuh

reveals that the DoubleBuffer is probably swapped on the host, where the `selector` member is flipped, see also
https://github.com/NVlabs/cub/blob/c3cceac115c072fb63df1836ff46d8c60d9eb304/cub/util_type.cuh

So I would just try what happens if you remove the sync and if unit tests still pass.

**Comment by mphoward** [comment]
I agree that CUB looks like it is just toggling flags in the host after dumping work into the stream, and so which pointer is valid should be known before the stream returns.

I was hesitant to just remove the sync because of this architecture and problem-size dependence for which buffer the result ends up in, as I'm not sure if my unit tests cover both cases. I can check if any tests happen to fail when swapping is disabled.

As the code is currently written, it is then probably safe to remove the sync and exchange the pointers in the thrust vectors on the host before the kernels return. (Cool! With the autotuners gone, this can be fully asynchronous.) Raw pointers are fed to CUB (and all kernels) so these are not connected to the members of the thrust vectors, and I think there should be no repercussions to swapping while the kernels are executing. I will feel more comfortable doing this with a `neighbor::device_ptr`, as then we have better control over which operations are permissible on the object and what is happening inside it.

**Comment by mphoward** [comment]
@jglaser I think that I've addressed all of your suggestions--they've definitely improved the code!

1. All mentions of `thrust` are gone. I've implemented two structures in `Memory.h`. One is the `shared_array`, which is a wrapper around a `shared_ptr` holding a managed allocation with a specifiable size. The other is the `buffered_array`, which mimics CUB's `DoubleBuffer`, and is now used in sorting (see below).

2. The HOOMD `Autotuner` mirror has been removed. There is a new class called `Tunable` that can be given a range or list of tunable parameters. It stores these internally in a set, so it is possible to quickly query if a set parameter is valid. It also supplies `getTunableParameters()`, which converts the set to a vector suitable for a HOOMD autotuner (see the benchmark as an example). The `LBVH` and `LBVHTraverser` both derive from this class (setting the tunable range in their constructor), so these methods are all exposed. Additionally, their APIs have been overhauled so that, for example, `build` can be called by supplying: (1) no block size and no stream, (2) no block size and a stream, or (3) a new struct `LaunchParameters` (defined by `Tunable`) that can set the block size and stream. When no block size is set, I found that using just 32 threads can reasonable performance on my consumer GPU for a LJ benchmark, but we can also revisit this with other hardware or systems. The same block size is used for all of my kernels, which seems to be pretty performant.

3. Your analysis of the CUB code seems correct, and the sync call is not required because the buffer flags are being flipped on the host. `buffered_array` gives an easy way to work with this type of data & keeping track of where the sorted codes/indexes are, and so I believe the build call is now fully asynchronous (provided that `setup` is called in advance to avoid memory allocations).

Let me know what you think of these changes, and I can update my HOOMD branch to be compatible with this design.

**Comment by jglaser** [comment]
Overall, this looks great! I am just asking for your confirmation that the `Scalar`->`float` demotion only affects the operations which are included in the `neighbor` library (example templates), but not those that will actually be defined in `NeighborListTreeGPU` in HOOMD, right?

I noticed the new `TranslateOp`. Now that the `image` variable in the traversal kernel is available both for `QueryOp::query()` and `QueryOp::refine()`, and no extra GPU registers would therefore be used, would it be possible to extend the `refine` signature with an extra image argument? That would avoid the `BoxDim` storage in HOOMD's `ParticleQueryOp` as we had discussed earlier. This suggestion is completely optional.

**Comment by jglaser** [comment]
Another small suggestion: you could improve the `FindCUB.cmake` by allowing for a user supplied hint, like this:
```
    find_path(CUB_INCLUDE_DIR
        NAMES cub/cub.cuh
        PATHS
        ${CUB_ROOT_DIR}
        $ENV{CUB_ROOT_DIR}
        NO_DEFAULT_PATH)
```

same probably for `upp11`

**Comment by mphoward** [comment]
> I am just asking for your confirmation that the `Scalar`->`float` demotion only affects the operations which are included in the `neighbor` library (example templates), but not those that will actually be defined in `NeighborListTreeGPU` in HOOMD, right?

Yes, that's correct. It was easier to just support floats in the examples and unit tests (for now). I may consider templating some of these later to take float or double to get better test coverage.

> I noticed the new `TranslateOp`. Now that the `image` variable in the traversal kernel is available both for `QueryOp::query()` and `QueryOp::refine()`, and no extra GPU registers would therefore be used, would it be possible to extend the `refine` signature with an extra image argument? That would avoid the `BoxDim` storage in HOOMD's `ParticleQueryOp` as we had discussed earlier. This suggestion is completely optional.

I think that the register usage might still go up if I made this change. I added the `TranslateOp` so that the image type could be float or double. I do stash the result of loading the image into a variable, but this is mostly for readability as it is immediately consumed by `QueryOp::get()`. `image` does not currently need to be held onto during traversal, but passing it to `refine` would require it to stay around. For this reason, I prefer not to add it as an argument at this time, but I would revisit this later if there were enough use cases.

**Comment by mphoward** [comment]
> Another small suggestion: you could improve the `FindCUB.cmake` by allowing for a user supplied hint

Good idea, I added `CUB_ROOT` and `ENV{CUB_ROOT}` to PATHS. In CMake >= 3.12, these can already be set by the user, but not for lower versions. To make sure the search order is consistent, I make two `find_path` calls in older CMake--one using the hints and `NO_DEFAULT_PATH`, and then one on the system path. If the first call is successful, the second will do nothing. In newer CMake, only the second call is required.

https://cmake.org/cmake/help/v3.11/command/find_path.html

https://cmake.org/cmake/help/v3.12/command/find_path.html

**Pull request merged**
