### PR TITLE
Enable HIP backend & runtime

### PR DESCRIPTION
**Pull request by mphoward**
This PR enables compilation on AMD GPUs using HIP as a backend. It uses the hipper runtime as a compatibility layer between HIP and CUDA. Setting `NEIGHBOR_HIP=ON` uses HIP as the backend, so the compiler can be HCC or NVCC, while `NEIGHBOR_HIP=OFF` uses the original CUDA backend (NVCC). Most of the changes to use this runtime are cosmetic find-and-replace.

The bigger sticking point was that HIP does not implement math rounding mode intrinsics. A new header `ApproximateMath.h` acts as another compatibility layer here, with functions called like `approx::fadd_ru(float x, float y)`. When compiling under CUDA or HIP+NVCC (`HIPPER_PLATFORM_NVCC`), the CUDA intrinsics are used directly. Under HIP+HCC, the normal float operation is used and `nextafterf` (in HIP, but not documented) is used to drive the result toward `-FLT_MAX` for `_rd` mode or `FLT_MAX` for `_ru` mode. The float operation should be in round-nearest mode, so the result of nextafterf should be either the same as the intrinsic OR the next representable float, making an error in one bit. It takes an extra instruction to do this, but it simplifies the code maintenance significantly.

I added a few unit tests for the approximate math and tested that this compiles with HIP (failure is at the linking stage because I don't know how to set the AMD target properly), but I don't have an AMD GPU to test it on. @jglaser could you help out with that?

I would like to go back later and add some torture tests to the bounding volume checks that use the approximate math intrinsics, but I will defer that to a later PR.

### CODE REVIEW

**Comment by mphoward** [comment]
@jglaser can you test this branch on AMD and let me know if it works for you? It passes CUDA build and test on brett. If so, please review for any additional feedback, and I will merge into `hoomd-3`, then merge `hoomd-3` into `master` for a new tagged release we can use in HOOMD.

**Comment by jglaser** [comment]
sorry it took me so long to get back to this. I am trying to build, but it can't find a upp11 dependency. I could install it, of course, but just asking whether it is an essential one.

**Comment by mphoward** [comment]
No problem. upp11 is needed for the unit tests, but since it is single-header, we can make it optional, as I did in hipper for catch2:

https://github.com/mphowardlab/hipper/blob/e0721c697c096aa00158a9576071456ff75b285d/tests/CMakeLists.txt#L15-L26

**Comment by jglaser** [comment]
hmm, is `catch2` better/simpler than `upp11`? If so, it would make sense to decide for either in both packages.

**Comment by mphoward** [comment]
I don't have a strong preference between either of them, but catch2 is actively developed and upp11 is not.  I think catch2 is a little better with supporting multiple cases with less code, but neighbor already used upp11 because of how closely integrated it was with hoomd, so I stuck with it. (I would have to go back and rewrite all of the "close to" equalities.) I think it's OK if the two use different test frameworks---I mostly meant that I could use a similar "find--if not download" to grab a upp11 header for neighbor.

**Comment by jglaser** [comment]
OK, I finally got it to compile on a `MI60`. Here's the result of the tests (both currently failing).
```
1: Test command: /home/users/coe0176/neighbor/build/test/approx_math_test
1: Test timeout computed to be: 10000000
1: random seed: 1591996290
1: /home/users/coe0176/neighbor/test/approx_math_test.cu(98): check result[1] (1.000000) > 1.0f (1.000000) failed
1: approx_math_test: FAIL
1: Run 1 tests with 1 failures
1/2 Test #1: approx_math_test .................***Failed    0.59 sec
test 2
    Start 2: lbvh_test

2: Test command: /home/users/coe0176/neighbor/build/test/lbvh_test
2: Test timeout computed to be: 10000000
2: random seed: 1591996291
2: lbvh_periodic_test: SUCCESS
2: Testing small LBVH build...
2: Testing small traverser...
2: lbvh_small_test: SUCCESS
2: lbvh_validate: SUCCESS
2: Testing LBVH build...
2: Testing traverser basics...
2: /home/users/coe0176/neighbor/test/lbvh_test.cu(154): check equal (((unsigned int)node.y >> 20) & 0x3ffu, 1023) failed
2: 	1022 vs 1023
2: lbvh_test: FAIL
2: Run 4 tests with 1 failures
2/2 Test #2: lbvh_test ........................***Failed    1.00 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   1.59 sec

The following tests FAILED:
	  1 - approx_math_test (Failed)
	  2 - lbvh_test (Failed)
Errors while running CTest
srun: error: node004: task 0: Exited with exit code 8
(hip-rocm) [coe0176@poplar build]$ 
```

any ideas?

**Comment by mphoward** [comment]
Hmmm, I suspect both tests are failing because the approximate math is not working right. Good thing you suggested writing tests for that!!

The round down test (`result[0]`) tells us nothing because the float cast of the double should be `1.0f`, so the first test that fails (in `result[1]`) is the round up intrinsic:

https://github.com/mphoward/neighbor/blob/68b00838416782657ebcae9c0dc7f60817a61ac8/test/approx_math_test.cu#L25-L27

This is just supposed to call the HIP intrinsic directly:

https://github.com/mphoward/neighbor/blob/68b00838416782657ebcae9c0dc7f60817a61ac8/include/neighbor/ApproximateMath.h#L61-L65

so there's no reason that this should pass for NVIDIA and fail for AMD, unless the intrinsic is not actually implemented correctly. Allegedly, these intrinsics are supported:

https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP-MATH.html#double2float-rd

But, I searched the HIP source code, and this is clearly not true:

https://github.com/ROCm-Developer-Tools/HIP/blob/386a0e0123d67b95b4c0ebb3ebcf1d1615758146/include/hip/hcc_detail/device_functions.h#L619-L627

Do you know any devs at AMD that you could ask about this?

We can workaround this by using `nextafter` at the cost of some extra instructions:

https://stackoverflow.com/questions/15294046/round-a-double-to-the-closest-and-greater-float

I've done this in a CPU code before, so I can try to patch it this way for the time being.

**Comment by jglaser** [comment]
I will check with the AMD folks.

**Pull request merged**
