### PR TITLE
Add AMD target architecture for tests

### PR DESCRIPTION
**Pull request by mphoward**
Support an AMD target, in the same was as CUDA target.

@jglaser

### CODE REVIEW

**Comment by jglaser** [comment]
Right now I am getting
```(hip-rocm) [coe0176@poplar test]$ srun ./approx_math_test 
random seed: 1593456049
unexpected test termination: Test terminated by signal
terminate called after throwing an instance of 'std::runtime_error'
  what():  Test terminated by signal
srun: error: node004: task 0: Aborted
```.
Probably because the right architecture for this platform (gfx906) is not included, only gfx900

**Comment by mphoward** [comment]
What would be the best "default" AMD architecture to support? I am not supporting lists of architectures in CUDA (just a single one), so I didn't intend to do that for AMD either. For CUDA, I use sm_35.

**Comment by jglaser** [comment]
I added more default architectures in  PR #21, which includes the present one

**Comment by mphoward** [comment]
- [ ] Support multiple NVCC targets
- [ ] Remove duplicate `gfx900` from AMD targets

**Pull request merged**
